from typing import TypeVar, Generic, Sequence

T = TypeVar("T")
class TaskSchedule(Generic[T]):
    def empty(self, timestamp:float) -> bool: ...
    def is_task_scheduled(self, task:T) -> bool: ...
    def push_task(self, timestamp:float, task:T) -> None: ...
    def pop_current_tasks(self, timestamp:float) -> Sequence[T]: ...
