[build-system]
requires = ["setuptools >= 75.0", "wheel", "Cython", "cymunk @ git+https://github.com/gerner/cymunk@f83e2d4", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/stellarpunk/_version.py"
