[build-system]
requires = ["setuptools >= 75.0", "wheel", "Cython >= 3.0", "cymunk @ git+https://github.com/gerner/cymunk@b3020d3", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/stellarpunk/_version.py"
