import numpy

class MarkovModel:
    def __init__(self, romanize:bool=False, titleize:bool=True, roman_numerals:bool=False, empty:bool=False) -> None: ...
    def train(self, filename:str, n:int=5) -> MarkovModel: ...
    def generate(self, random:numpy.random.Generator) -> str: ...
    def save(self, filename:str) -> MarkovModel: ...
    def load(self, filename:str) -> MarkovModel: ...
